SELECT
--INFORMACOES BASICAS DOS PRODUTOS
PRO.CODPROD
,PRO.DESCRPROD
,PRO.AD_MODELOREF
,GRU.DESCRGRUPOPROD
--ULTIMA DATA DE MODIFICACAO DO PRODUTO
,PRO.DTALTER
--DIFERENCA DE DATAS ENTRE A DATA DE MODIFICACAO DO PRODUTO E A DATA ATUAL DO SISTEMA
,DATEDIFF(MONTH, PRO.DTALTER, GETDATE()) AS [DIFERENCA]
--VALOR TOTAL DE VENDAS DO PRODUTO
,[VLR] = SUM (CASE WHEN CAB.CODTIPOPER IN (1110,1112,1101) THEN ITE.VLRTOT END)
--QUANTIDADE DE NOTAS DO PRODUTO
,[QTD_NOTAS] = COUNT (CASE WHEN CAB.CODTIPOPER IN (1110,1112,1101) THEN ITE.NUNOTA END)
--MEDIA ENTRE VALOR VENDIDO E POPULARIDADE
,[MEDIA] = SUM (CASE WHEN CAB.CODTIPOPER IN (1110,1112,1101) THEN ITE.VLRTOT END) /
           COUNT (CASE WHEN CAB.CODTIPOPER IN (1110,1112,1101) THEN ITE.NUNOTA END)
--QTD DE ESTOQUE TRANSFERIDO PARA O LOCAL AVARIA 103
,[AVARIAS] = SUM (CASE WHEN CAB.CODTIPOPER=1890 AND ITE.CODLOCALORIG=103 THEN ITE.QTDNEG END)
FROM
TGFPRO PRO
,TGFCAB CAB
,TGFITE ITE
,TGFGRU GRU
WHERE
PRO.CODPROD=ITE.CODPROD
AND ITE.NUNOTA = CAB.NUNOTA
AND PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
AND PRO.CODGRUPOPROD <= 1990000
AND CAB.CODTIPOPER IN (1110,1112,1101,1890)
GROUP BY
PRO.CODPROD
,PRO.DESCRPROD
,PRO.AD_MODELOREF
,GRU.DESCRGRUPOPROD
,PRO.DTALTER
HAVING
--EVITA QUE VLR FIQUE VAZIO
SUM (CASE WHEN CAB.CODTIPOPER IN (1110,1112,1101) THEN ITE.VLRTOT END) IS NOT NULL
ORDER BY
SUM (CASE WHEN CAB.CODTIPOPER=1890 AND ITE.CODLOCALORIG=103 THEN ITE.QTDNEG END) DESC
