SELECT
--NOMEIA AS EMPRESAS DE FORMA SIMPLES
    CASE
    WHEN CAB.CODEMP=1 THEN 'PADRE EUTÍQUIO'
    WHEN CAB.CODEMP=2 THEN 'DR. FREITAS'
    WHEN CAB.CODEMP=4 THEN 'PEDRO MIRANDA'
    END AS [EMPRESA],
--NOMEIA O CAMPO DE ENTREGA DE FORMA SIMPLES
CAB.DTNEG,
    CASE
    WHEN CAB.AD_ENTREGA=1 THEN 'LOJA ENTREGA'
    WHEN CAB.AD_ENTREGA=2 THEN 'CLIENTE LEVOU'
    END AS [ENTREGA],
ITE.AD_LOCALSAIDA,
ITE.AD_MOSTRUARIO,
CAB.NUMNOTA,
ITE.QTDNEG,
ITE.CODPROD,
PRO.DESCRPROD
FROM
TGFCAB AS CAB
,TGFITE AS ITE
,TGFPRO AS PRO
WHERE
CAB.NUNOTA = ITE.NUNOTA
AND ITE.CODPROD=PRO.CODPROD
--SELECIONA OS RESGISTRO DO DIA ANTERIOR
AND CAB.DTNEG = DATEADD(day, -1, convert(date, GETDATE()))
AND CAB.CODTIPOPER IN (1110,1101,1112)
ORDER BY
CAB.AD_ENTREGA,
CAB.NUMNOTA
