SELECT
  CAB.DTNEG AS [DATA]
  ,CAB.CODEMP AS [LOJA]
  ,'PA' AS [UF]
  ,'BELÉM' AS [CIDADE]
  ,GRU.DESCRGRUPOPROD AS [CATEGORIA]
  ,ITE.CODPROD AS [COD_EAN]
  ,PRO.MARCA AS [MARCA/FABRICANTE]
  ,PRO.AD_MODELOREF AS [MODELO]
  ,PRO.DESCRPROD AS [DESCRICAO COMPLETA DO PRODUTO]
  ,ITE.QTDNEG AS [QTDE]
  ,ITE.VLRUNIT AS [PREÇO UNITÁRIO]
  ,ITE.VLRTOT AS [FATURAMENTO TOTAL]

FROM
  TGFCAB CAB
  ,TGFITE ITE
  ,TGFPRO PRO
  ,TGFGRU GRU

WHERE
  CAB.NUNOTA=ITE.NUNOTA
  AND ITE.CODPROD=PRO.CODPROD
  AND PRO.CODGRUPOPROD=GRU.CODGRUPOPROD
  AND DTNEG>='16/04/2018'
  AND DTNEG<='22/04/2018'
  AND CAB.CODTIPOPER IN (1112,1101)

ORDER BY
  CAB.DTNEG
  ,CAB.CODEMP 
  ,ITE.CODPROD
