-- CONTRATO DE TRABALHO 8HS

SELECT RTRIM(FUN.NOMEFUNC) [NOMEFUNC]
      ,CASE WHEN FUN.NACIONALIDADE = 10 THEN 'BRASILEIRO'
			END AS [NACIONALIDADE]
      ,CASE WHEN FUN.ESTADOCIVIL = 1 THEN 'SOLTEIRO'
			WHEN FUN.ESTADOCIVIL = 2 THEN 'CASADO'
			WHEN FUN.ESTADOCIVIL = 3 THEN 'VIUVO'
			WHEN FUN.ESTADOCIVIL = 4 THEN 'SEPARADO JUDICIALMENTE'
			WHEN FUN.ESTADOCIVIL = 5 THEN 'DESQUITADO'
			WHEN FUN.ESTADOCIVIL = 6 THEN 'DIVORCIADO'
			WHEN FUN.ESTADOCIVIL = 7 THEN 'UNIAO ESTAVEL'
			END AS [ESTADOCIVIL]
      ,RTRIM(FCO.DESCRFUNCAO) [DESCRFUNCAO]
      ,RTRIM(FUN.IDENTIDADE) [IDENTIDADE]
      ,RTRIM([sankhya].[FORMATARCPF](CPF)) [CPF]
      ,RTRIM([sankhya].[FORMATARPIS](FUN.PIS)) [PIS]
      ,FCO.CODCBO
      ,FUN.NUMCPS
      ,FUN.SERIECPS
      ,UPPER(RTRIM(RUA.TIPO) + ' ' + RTRIM(RUA.NOMEEND) + ' nº ' + RTRIM(FUN.NUMEND) + ' ,' +
             RTRIM([sankhya].[FORMATARCEP](FUN.CEP)) + ' ,' + RTRIM(BAI.NOMEBAI) + ' ,' + RTRIM(CID.NOMECID) + ' ,' +
             RTRIM(UFS.DESCRICAO) + ' ,' + RTRIM(PAI.DESCRICAO)) [END_CONTRATADO]
      ,CONVERT (VARCHAR (12), FUN.DTADM, 103) [DTADM]
      ,DATEDIFF(DAY, FUN.DTADM, FUN.DTVENCEXP1)+1 [DIASPERIODO1]
      ,CONVERT (VARCHAR (12), FUN.DTVENCEXP1, 103) [DTVENCEXP1]
      ,DATEDIFF(DAY, FUN.DTADM, FUN.DTVENCEXP2)+1 [DIASPERIODO2]
      ,CONVERT (VARCHAR (12), FUN.DTVENCEXP2, 103) [DTVENCEXP2]
      ,RTRIM([sankhya].[FORMATAVALOR](FUN.SALBASE,'.',',')) SALBASE
      ,RTRIM(CGH.DESCRCARGAHOR) [DESCRCARGAHOR]
      -- INFOS DA EMPRESA
      ,FUN.CODEMP
      ,RTRIM(EMP.RAZAOSOCIAL) [RAZAOSOCIAL]
      ,UPPER(( SELECT RTRIM(RUA.TIPO) + ' ' + RTRIM(RUA.NOMEEND) + ', ' + RTRIM(EMP1.NUMEND) + ', ' +
	                  RTRIM(BAI.NOMEBAI) + ', ' + RTRIM(CID.NOMECID) + ', ' + RTRIM([sankhya].[FORMATARCEP](EMP1.CEP))
		         FROM TSIEMP EMP1
			         ,TSIEND RUA
			         ,TSIBAI BAI
			         ,TSICID CID
		        WHERE EMP1.CODEND = RUA.CODEND
		          AND EMP1.CODBAI = BAI.CODBAI
		          AND EMP1.CODCID = CID.CODCID
		          AND EMP1.CODEMP=EMP.CODEMP   )) [END_CONTRATANTE]
	  ,RTRIM([sankhya].[FORMATARCNPJ](EMP.CGC)) [CGC]
  FROM TFPFUN FUN
      ,TFPFCO FCO
      ,TSIEND RUA
      ,TSIBAI BAI
      ,TSICID CID
      ,TSIUFS UFS
      ,TSIPAI PAI
      ,TSIEMP EMP
      ,TFPCGH CGH
 WHERE FUN.CODFUNCAO = FCO.CODFUNCAO
   AND FUN.CODEND = RUA.CODEND
   AND FUN.CODBAI = BAI.CODBAI
   AND FUN.CODCID = CID.CODCID
   AND FUN.CODCARGAHOR = CGH.CODCARGAHOR
   AND CID.UF = UFS.CODUF
   AND FUN.CODEMP = EMP.CODEMP
   AND UFS.CODPAIS = PAI.CODPAIS
   AND FUN.CODEMP = 1
   AND FUN.CODFUNC = 60
