SELECT
ESTOQUE.CODPROD
,ESTOQUE.DESCRPROD
,ESTOQUE.ESTOQUE
,ESTOQUE.ESTOQUE * CUSTO.CUSMEDICM AS [CUSTO MEDIO COM ICMS]
,ESTOQUE.ESTOQUE * CUSTO.CUSSEMICM AS [CUSTO MEDIO SEM ICMS]
,ESTOQUE.ESTOQUE * CUSTO.CUSREP AS [CUSTO REPOSICAO]
,ESTOQUE.ESTOQUE * CUSTO.CUSVARIAVEL AS [CUSTO VARIAVEL]
,ESTOQUE.ESTOQUE * CUSTO.CUSGER AS [CUSTO GERENCIAL]
,ESTOQUE.ESTOQUE * CUSTO.CUSMED AS [CUSTO MEDIO]
,ESTOQUE.ESTOQUE * CUSTO.ENTRADACOMICMS AS [ENTRADA COM ICMS]
,ESTOQUE.ESTOQUE * CUSTO.ENTRADASEMICMS AS [ENTRADA SEM ICMS]
FROM
(
SELECT
EST.CODPROD
,PRO.DESCRPROD
,ESTOQUE
FROM
TGFEST AS EST
,TGFPRO AS PRO
WHERE
EST.CODPROD = PRO.CODPROD
AND ESTOQUE>0
AND PRO.CODGRUPOPROD >= '1000000'
AND PRO.CODGRUPOPROD <= '1139999'
) AS ESTOQUE
INNER JOIN
(
SELECT 
CODPROD
,CUSMEDICM
,CUSSEMICM
,CUSREP
,CUSVARIAVEL
,CUSGER
,CUSMED
,ENTRADACOMICMS
,ENTRADASEMICMS
FROM 
TGFCUS AS CU1
WHERE
DTATUAL = (SELECT MAX(DTATUAL) FROM TGFCUS AS CU2 WHERE CU1.CODPROD=CU2.CODPROD)
) AS CUSTO

ON ESTOQUE.CODPROD = CUSTO.CODPROD

ORDER BY
ESTOQUE.DESCRPROD
