SELECT ITE.CODPROD
      ,PRO.DESCRPROD + ' Mod. ' + PRO.AD_MODELOREF AS [DESCRPROD]
      ,ITE.QTDNEG
      ,CAB.DTMOV
      -- PREÇO DE VENDA
      ,( SELECT ME.VLRVENDA
           FROM TGFNTA NTA
               ,TGFTAB MT
               ,TGFEXC ME
          WHERE NTA.CODTAB = MT.CODTAB
            AND MT.NUTAB = ME.NUTAB
            AND NTA.CODTAB =  0
            AND ME.CODPROD = ITE.CODPROD
            AND MT.DTVIGOR = (SELECT MAX(MT.DTVIGOR)
		                        FROM TGFNTA NTA, TGFTAB MT, TGFEXC ME
		                       WHERE NTA.CODTAB = MT.CODTAB
		                         AND MT.NUTAB = ME.NUTAB
		                         AND NTA.CODTAB = 0
		                         AND ME.CODPROD = ITE.CODPROD)) AS VLR_VENDA
      -- ESTOQUE DE VENDA NA MATRIZ
      ,ISNULL(
       ( SELECT EST1.ESTOQUE 
           FROM TGFEST EST1 
          WHERE EST1.CODPROD=ITE.CODPROD 
            AND EST1.CODEMP=1 
            AND EST1.CODLOCAL = 102 ), 0) AS EST_MTZ
      -- ESTOQUE DE VENDA NA PEDREIRA
      ,ISNULL(
       ( SELECT EST1.ESTOQUE 
           FROM TGFEST EST1 
          WHERE EST1.CODPROD=ITE.CODPROD 
            AND EST1.CODEMP=4 
            AND EST1.CODLOCAL = 102 ), 0) AS EST_PED
      -- ESTOQUE DE VENDA NO DEPOSITO
      ,ISNULL(
       ( SELECT EST1.ESTOQUE 
           FROM TGFEST EST1 
          WHERE EST1.CODPROD=ITE.CODPROD 
            AND EST1.CODEMP=2 
            AND EST1.CODLOCAL = 102 ), 0) AS EST_DEP
      -- ESTOQUE DE AVARIAS
      ,ISNULL(
       ( SELECT EST1.ESTOQUE 
           FROM TGFEST EST1 
          WHERE EST1.CODPROD=ITE.CODPROD 
            AND EST1.CODLOCAL = 103 ), 0) AS AVARIAS
 FROM TGFCAB CAB
     ,TGFITE ITE
     ,TGFPRO PRO
WHERE CAB.NUNOTA=ITE.NUNOTA
  AND ITE.CODPROD=PRO.CODPROD
  AND CAB.CODTIPOPER IN (1402, 1434, 1403, 1409, 1418, 1438, 1437)
  AND PRO.CODGRUPOPROD NOT IN (2040000, 2050000, 2070200,
                               3010000, 3020000, 3030000,
                               3040000, 2000000, 1990000,
                               3100000, 3070000)
  AND CAB.DTMOV = DATEADD(day, -1, convert(date, GETDATE()))
--AND CAB.DTMOV = '20/08/2018'
  AND CAB.STATUSNOTA='L'
ORDER BY PRO.DESCRPROD