-- principal
SELECT PRINCIPAL.NUNOTA
      ,PRINCIPAL.NUMNOTA
      ,PRINCIPAL.NOMEPARC
      ,PRINCIPAL.VLRNOTA
      ,PRINCIPAL.VLRFRETE
      ,PRINCIPAL.CODPROD
      ,PRINCIPAL.DESCRPROD
      ,PRINCIPAL.QTDNEG
      ,PRINCIPAL.VLRUNIT
      ,PRINCIPAL.VLRTOT
      ,PRINCIPAL.ALIQIPI
      ,PRINCIPAL.VLRIPI
      ,COMPRA.VLR_COMPRA [ULT_COMPRA]
      ,VENDA.PRECO_VENDA [ULT_VENDA]

FROM ( SELECT CAB.NUNOTA
             ,CAB.NUMNOTA
             ,CAB.CODPARC
             ,PAR.NOMEPARC
             ,CAB.VLRNOTA
             ,ITE.CODPROD
             ,RTRIM(PRO.DESCRPROD) + ' - ' + RTRIM(PRO.MARCA) + ' - ' + RTRIM(PRO.AD_MODELOREF) [DESCRPROD]
             ,ITE.QTDNEG
             ,ITE.VLRUNIT
             ,ITE.VLRTOT
             ,ITE.VLRIPI
			 ,ITE.ALIQIPI
			 ,CAB.VLRFRETE
         FROM TGFCAB CAB ,TGFITE ITE ,TGFPAR PAR ,TGFPRO PRO
	    WHERE CAB.NUNOTA=ITE.NUNOTA
          AND CAB.CODPARC=PAR.CODPARC
          AND ITE.CODPROD=PRO.CODPROD ) AS PRINCIPAL

-- PRECO VENDA
    ,( SELECT PRO.CODPROD, ME.VLRVENDA AS [PRECO_VENDA]
         FROM TGFNTA NTA ,TGFTAB MT ,TGFEXC ME, TGFPRO PRO
        WHERE NTA.CODTAB = MT.CODTAB
          AND MT.NUTAB = ME.NUTAB
          AND ME.CODPROD = PRO.CODPROD
          AND NTA.CODTAB =  0
          AND ME.CODPROD = PRO.CODPROD
          AND MT.DTVIGOR = (SELECT MAX(MT.DTVIGOR)
                              FROM TGFNTA NTA, TGFTAB MT, TGFEXC ME
                             WHERE NTA.CODTAB = MT.CODTAB
                               AND MT.NUTAB = ME.NUTAB
                               AND NTA.CODTAB = 0
                               AND ME.CODPROD = PRO.CODPROD) ) AS VENDA

-- PRECO COMPRA
    ,( SELECT DISTINCT
              CAB.DTNEG
             ,ITE.CODPROD
             ,ITE.VLRUNIT [VLR_COMPRA]
         FROM TGFCAB CAB, TGFITE ITE
        WHERE CAB.NUNOTA = ITE.NUNOTA
          AND CAB.CODTIPOPER IN (1413,1403,1412,1402,1417,1409,1418,1403,1434,1433,1436,1438,1417,1437,1403,1409,1418,1453,1441)
          AND CAB.DTNEG = (SELECT MIN(MENOR.DTNEG)
							-- NO SELECT DENTRO DO FROM USA O ORDER PARA COLOCAR AS DATAS DA MAIOR PARA A MENOR
							-- TOP2 PARA PEGAR OS DOIS REGISTROS MAIS "À CIMA" E O DISTINCT PARA NÃO HAVER REPETIÇÕES
							-- E O SELECT EXTERNO COM O MIN PARA PEGAR A MENOR DATA, QUE NESSE CASO VAI SER A SEGUNDA DATA.
							FROM (SELECT DISTINCT TOP (2) CAB1.DTNEG
							        FROM TGFCAB CAB1, TGFITE ITE1
							       WHERE CAB1.NUNOTA=ITE1.NUNOTA
						             AND CAB1.CODTIPOPER IN (1413,1403,1412,1402,1417,1409,1418,1403,1434,1433,1436,1438,1417,1437,1403,1409,1418,1453,1441)
							         AND ITE1.CODPROD = ITE.CODPROD
							    ORDER BY CAB1.DTNEG DESC )MENOR) ) AS COMPRA

WHERE PRINCIPAL.CODPROD = VENDA.CODPROD
  AND PRINCIPAL.CODPROD = COMPRA.CODPROD
  AND PRINCIPAL.NUNOTA = $P{NUNOTA}
ORDER BY PRINCIPAL.CODPROD