-- principal
SELECT

PRINCIPAL.CODPROD
,PRINCIPAL.DESCRPROD
,PRINCIPAL.VLRUNIT
,VENDA.PRECO_VENDA

FROM

(SELECT
CAB.NUNOTA
,CAB.NUMNOTA
,CAB.CODPARC
,PAR.NOMEPARC
,CAB.VLRNOTA
,ITE.CODPROD
,PRO.DESCRPROD + ' - ' + PRO.MARCA + ' - ' +PRO.AD_MODELOREF [DESCRPROD]
,ITE.QTDNEG
,ITE.VLRUNIT
,ITE.VLRTOT
,ITE.VLRIPI
,ITE.ALIQIPI
,CAB.VLRFRETE

FROM
TGFCAB CAB
,TGFITE ITE
,TGFPAR PAR
,TGFPRO PRO

WHERE
CAB.NUNOTA=ITE.NUNOTA
AND CAB.CODPARC=PAR.CODPARC
AND ITE.CODPROD=PRO.CODPROD
--AND CAB.NUMNOTA=52696
) AS PRINCIPAL

,

(
-- PRECO VENDA

SELECT DISTINCT
PRO.CODPROD,
PRO.DESCRPROD,
PRO.AD_MODELOREF ,
(SELECT ME.VLRVENDA
FROM TGFNTA NTA
, TGFTAB MT
, TGFEXC ME
 WHERE NTA.CODTAB = MT.CODTAB
AND MT.NUTAB = ME.NUTAB
AND NTA.CODTAB =  0
AND ME.CODPROD = PRO.CODPROD
AND MT.DTVIGOR = (SELECT MAX(MT.DTVIGOR)
FROM TGFNTA NTA, TGFTAB MT, TGFEXC ME
WHERE NTA.CODTAB = MT.CODTAB
AND MT.NUTAB = ME.NUTAB
AND NTA.CODTAB = 0
AND ME.CODPROD = PRO.CODPROD)) AS PRECO_VENDA
FROM TGFEST EST,
TGFPRO PRO
WHERE EST.CODPROD = PRO.CODPROD
AND EST.CODEMP IN (1,2,4)
AND EST.ESTOQUE > 0
) AS VENDA

WHERE 
PRINCIPAL.CODPROD=VENDA.CODPROD
AND PRINCIPAL.NUMNOTA=52696

ORDER BY
PRINCIPAL.CODPROD
