DECLARE @ANO INT
DECLARE @EMP INT

SET @ANO=:ano
SET @EMP=:emp

SELECT
CAB.CODTIPOPER
,TIP.DESCROPER
,SUM(CAB.VLRNOTA) AS [VLR]

,[JAN] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=1 THEN CAB.VLRNOTA END)
,[FEV] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=2 THEN CAB.VLRNOTA END)
,[MAR] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=3 THEN CAB.VLRNOTA END)
,[ABR] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=4 THEN CAB.VLRNOTA END)
,[MAI] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=5 THEN CAB.VLRNOTA END)
,[JUN] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=6 THEN CAB.VLRNOTA END)
,[JUL] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=7 THEN CAB.VLRNOTA END)
,[AGO] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=8 THEN CAB.VLRNOTA END)
,[SET] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=9 THEN CAB.VLRNOTA END)
,[OUT] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=10 THEN CAB.VLRNOTA END)
,[NOV] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=11 THEN CAB.VLRNOTA END)
,[DEZ] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=@EMP AND MONTH(DTNEG)=12 THEN CAB.VLRNOTA END)


FROM
TGFCAB AS CAB

INNER JOIN
VIEWTOPS AS TIP
ON CAB.CODTIPOPER=TIP.CODTIPOPER

WHERE
CAB.CODTIPOPER IN (1401,1402,1403,1404,1405,1408,1409,1410,1411,1412,1413,1414,1415,1417,1418,
1419,1422,1425,1426,1429,1431,1432,1433,1434,1436,1437,1438,1450,1452,1453)
AND YEAR(DTNEG)=@ANO

GROUP BY
CAB.CODTIPOPER
,TIP.DESCROPER

ORDER BY
SUM(CAB.VLRNOTA) DESC 
