-- DECLARANDO VARIAVEL PRA FACILITAR A TROCA DE ANO

DECLARE @ANO INT
SET @ANO=:ano

SELECT
-- FORMA DE NOMEAR OS MESES
CASE
    WHEN MONTH(DTFATUR) = 1 THEN 'JAN'
    WHEN MONTH(DTFATUR) = 2 THEN 'FEV'
    WHEN MONTH(DTFATUR) = 3 THEN 'MAR'
    WHEN MONTH(DTFATUR) = 4 THEN 'ABR'
    WHEN MONTH(DTFATUR) = 5 THEN 'MAI'
    WHEN MONTH(DTFATUR) = 6 THEN 'JUN'
    WHEN MONTH(DTFATUR) = 7 THEN 'JUL'
    WHEN MONTH(DTFATUR) = 8 THEN 'AGO'
    WHEN MONTH(DTFATUR) = 9 THEN 'SET'
    WHEN MONTH(DTFATUR) = 10 THEN 'OUT'
    WHEN MONTH(DTFATUR) = 11 THEN 'NOV'
    WHEN MONTH(DTFATUR) = 12 THEN 'DEZ'

END AS [REFERENCIA]

-- SOMATORIO DA MATRIZ
,[MTZ] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=1 THEN CAB.VLRNOTA END)
-- SOMATORIO FILIAL
,[PED] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=4 THEN CAB.VLRNOTA END)
-- SOMATORIO DEPOSITO
,[DEP] = SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=2 THEN CAB.VLRNOTA END)
-- TOTAL DAS UNIDADES, DETALHE INTERESSANTE, ALGUMAS COLUNAS FICAM NULAS O QUE DEIXA A SOMA ERRADA, 
-- A FORMA DE CORRIGIR É COLOCAR ISNULL( EXPRESSAO ,0) E QUANDO FOR NULO O SQL TROCA PARA 0
,[SOMA] = ISNULL((SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=1 THEN CAB.VLRNOTA END)),0)
+ISNULL((SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=4 THEN CAB.VLRNOTA END)),0)
+ISNULL((SUM(CASE WHEN YEAR(CAB.DTFATUR) = @ANO AND CAB.CODEMP=2 THEN CAB.VLRNOTA END)),0)

FROM
TGFCAB AS CAB

INNER JOIN
VIEWTOPS AS TIP
ON CAB.CODTIPOPER=TIP.CODTIPOPER

WHERE
-- TOPS DE DESPESA
CAB.CODTIPOPER IN (1401,1402,1403,1404,1405,1408,1409,1410,1411,1412,1413,1414,1415,1417,1418,1419,1422,1425,1426,1429,1431,1432,1433,1434,1436,1437,1438,1450,1452,1453)

AND YEAR(CAB.DTFATUR) = @ANO
-- IMPORTANTE COLOCAR AS 3 UNIDADES AQUI
AND CODEMP IN (1,4,2)


GROUP BY
MONTH(DTFATUR)

ORDER BY
MONTH(DTFATUR)
