-- SELECT EXTERNO PARA UTILIZAR FILTRO DE QUANTIDADE DE DIAS
-- POR ALGUM MOTIVO SE COLOCA NA CONDIÇÃO INTERNA O FILTRO 
-- FICA INCORRETO E TRAS PRODUTOS FORA DOLIMITE ESTABELECIDO
SELECT * FROM (   
SELECT CAB.CODEMP
     ,CAB.DTNEG
     ,MIN(DATEDIFF(DAY,CAB.DTFATUR,SYSDATETIME())) AS DIAS
     ,EST.ESTOQUE
     ,ITE.CODPROD
     ,PRO.DESCRPROD
     ,PRO.AD_MODELOREF [MODELO]
     ,PRO.MARCA         
     -- QUERY PARA RETORNAR O PREÇO DE VENDA DE UM PRODUTO
     ,(  SELECT ME.VLRVENDA
           FROM TGFNTA NTA
               ,TGFTAB MT
               ,TGFEXC ME
          WHERE NTA.CODTAB = MT.CODTAB
            AND MT.NUTAB = ME.NUTAB
            AND NTA.CODTAB = 0
            AND ME.CODPROD = ITE.CODPROD
            AND MT.DTVIGOR = (  SELECT MAX(MT.DTVIGOR  )
                                  FROM TGFNTA NTA
                                      ,TGFTAB MT
                                      ,TGFEXC ME
                                 WHERE NTA.CODTAB = MT.CODTAB
                                   AND MT.NUTAB = ME.NUTAB
                                   AND NTA.CODTAB = 0
                                   AND ME.CODPROD = ITE.CODPROD  )  ) AS [VLRVENDA]
 FROM TGFITE ITE
     ,TGFCAB CAB
     ,TGFPRO PRO
     ,TGFEST EST
WHERE ITE.NUNOTA = CAB.NUNOTA
  AND ITE.CODPROD = PRO.CODPROD
  AND ITE.CODPROD = EST.CODPROD
  AND EST.CODEMP = ITE.CODEMP
  AND EST.ESTOQUE >= 0
  AND CAB.CODEMP = 4
  AND CAB.CODTIPOPER IN (1112, 1110, 1101)
  -- QUERY PARA VERIFICAR A ULTIMA DATA DE VENDA DE UM PRODUTO
  AND CAB.DTNEG = (  SELECT MAX(CAB1.DTNEG)
                       FROM TGFCAB CAB1
                           ,TGFITE ITE1
                      WHERE CAB1.NUNOTA=ITE1.NUNOTA
                            AND ITE1.CODPROD=ITE.CODPROD
                            AND CAB1.CODTIPOPER IN (1112, 1110, 1101)  )
GROUP BY CAB.CODEMP
     ,CAB.DTNEG
     ,EST.ESTOQUE
     ,ITE.CODPROD
     ,PRO.DESCRPROD
     ,PRO.AD_MODELOREF
     ,PRO.MARCA
 ) REGISTRO
 -- DEFINICAO DA QUANTIDADE DE DIAS
 WHERE REGISTRO.DIAS>=90
 ORDER BY REGISTRO.DIAS DESC
