SELECT
FOL.CODEMP
,FOL.CODFUNC
,FUN.NOMEFUNC
,CASE
WHEN DATEPART(MONTH, REFERENCIA)=1 THEN ‘JAN/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=2 THEN ‘FEV/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=3 THEN ‘MAR/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=4 THEN ‘ABR/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=5 THEN ‘MAI/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=6 THEN ‘JUN/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=7 THEN ‘JUL/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=8 THEN ‘AGO/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=9 THEN ‘SET/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=10 THEN ‘OUT/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=11 THEN ‘NOV/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
WHEN DATEPART(MONTH, REFERENCIA)=12 THEN ‘DEZ/’ + CAST(YEAR(FOL.REFERENCIA) AS VARCHAR(5))
END AS [REFERENCIA]

,[INSS] = SUM(CASE WHEN FOL.CODEVENTO IN (922,902,921,901,910,911,912,900,923) THEN FOL.VLREVENTO END)
,[IRRF] = SUM(CASE WHEN FOL.CODEVENTO IN (904,905,915,907,908,909,913,914,917) THEN FOL.VLREVENTO END)

,[INNS-13º] = SUM(CASE WHEN FOL.CODEVENTO IN (903) THEN FOL.VLREVENTO END)
,[IRRF-13º] = SUM(CASE WHEN FOL.CODEVENTO IN (906) THEN FOL.VLREVENTO END)

FROM
TFPFOL AS FOL

INNER JOIN
TFPEVE AS EVE
ON FOL.CODEVENTO = EVE.CODEVENTO

INNER JOIN
TFPFUN AS FUN
ON FOL.CODFUNC=FUN.CODFUNC

WHERE
FUN.CODEMP=FOL.CODEMP
AND FOL.CODFUNC=/*Cód. Funcionário*/
AND FOL.CODEMP=/*Cód. da Empresa*/
AND YEAR(REFERENCIA)=/*Ano*/

GROUP BY
FOL.REFERENCIA
,FOL.CODEMP
,FOL.CODFUNC
,FUN.NOMEFUNC

ORDER BY
MONTH(FOL.REFERENCIA)
