/*GERAR MEDIA DE UMA LISTA DE COUNT*/

/*ESA PARTE FAZ MÉDIA*/
SELECT AVG(QTD) AS QTD
  FROM (
  
    /*ESSA PARTE GERA A LISTA DO COUNT*/
    SELECT
      CAST(COUNT(NUNOTA) AS FLOAT) AS QTD
    FROM
      TGFCAB
    WHERE
      CODTIPOPER IN (1112, 1101, 1110)
      AND CODPARC NOT IN (3,193)
    GROUP BY
      CODPARC
      
 ) AS QTDS
