SELECT
  CAB.DTNEG
    ,CASE
    WHEN CAB.AD_ENTREGA=1 THEN 'LOJA ENTREGA'
    WHEN CAB.AD_ENTREGA IS NULL THEN 'VERIFICAR ENTREGA'
    END AS [ENTREGA]
  ,CAB.CODEMP
  ,CAB.NUNOTA
  ,CAB.NUMNOTA
  ,CAB.CODTIPOPER
  ,TIP.DESCROPER
  ,CAB.CODVEND
  ,VEN.APELIDO
  ,CAB.CODPARC
  ,PAR.NOMEPARC
  ,BAI.NOMEBAI

FROM
  TGFCAB CAB
  ,TGFPAR PAR
  ,TGFVEN VEN
  ,VIEWTOPS TIP
  ,TSIBAI BAI

WHERE
  CAB.CODPARC=PAR.CODPARC
  AND CAB.CODVEND = VEN.CODVEND
  AND CAB.CODTIPOPER = TIP.CODTIPOPER
  AND PAR.CODBAI = BAI.CODBAI
  AND CAB.CODTIPOPER IN (1160)
  AND CAB.PENDENTE='S'
  AND CAB.CODPARC NOT IN (1,2,3,4)
  AND (CAB.AD_ENTREGA=1 OR CAB.AD_ENTREGA IS NULL)

ORDER BY
  CAB.DTNEG DESC
