-- Variáveis para o período (mês / ano) e código da empresa
DECLARE @DT_INICIO DATE
SET @DT_INICIO = '01/06/2018'
DECLARE @DT_FIM DATE
SET @DT_FIM =  '1/06/2018'
DECLARE @EMP INT
SET @EMP = 1

SELECT 
  CAB.DTNEG
  ,NAT.DESCRNAT
  ,SUM(CAB.VLRNOTA) AS SAIDA

FROM
  TGFCAB CAB
  ,TGFNAT NAT

WHERE
  CAB.CODTIPOPER = 1304
  AND CAB.CODNAT = NAT.CODNAT
  AND CAB.DTNEG >= @DT_INICIO
  AND CAB.DTNEG <= @DT_FIM
  AND CAB.CODEMP=@EMP

GROUP BY
  CAB.DTNEG
  ,NAT.DESCRNAT


ORDER BY
  CAB.DTNEG
