DECLARE @YEAR int
SET @YEAR=2018
DECLARE @MONTH int
SET @MONTH=6
DECLARE @EMP int
SET @EMP=4

SELECT * FROM (
(
------------------------------
SELECT ELETROS.CODEMP
      ,ELETROS.CODVEND
      ,ELETROS.APELIDO
      ,(ELETROS.QTDNEG+MOVEIS.QTDNEG) [TOTAL]
      ,((100 * ELETROS.QTDNEG) / (ELETROS.QTDNEG+MOVEIS.QTDNEG)) [ELETROS]
     ,((100 * MOVEIS.QTDNEG) / (ELETROS.QTDNEG+MOVEIS.QTDNEG)) [MOVEIS]
FROM (
SELECT 'ELETROS' [GRUPO]
      ,(
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1110,1101,1112) THEN ITE.VLRTOT-ITE.VLRDESC END),0) -
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1201) THEN ITE.VLRTOT-ITE.VLRDESC END),0)) [QTDNEG]
      ,ITE.CODVEND
      ,VEN.APELIDO
      ,VEN.CODEMP
FROM TGFCAB CAB
    ,TGFITE ITE
    ,TGFPRO PRO
    ,TGFVEN VEN
WHERE CAB.NUNOTA = ITE.NUNOTA
  AND VEN.TIPVEND='V'
  AND PRO.CODPROD = ITE.CODPROD
  AND ITE.CODVEND = VEN.CODVEND
  AND YEAR(CAB.DTNEG) = @YEAR
  AND MONTH(CAB.DTNEG) = @MONTH
  AND VEN.CODEMP=@EMP
  AND CAB.CODTIPOPER IN (1110,1101,1112,1201)
  AND ITE.CODVEND NOT IN (0,22,202)
  AND ((CODGRUPOPROD>='01010000' AND CODGRUPOPROD<='01029999') OR 
       (CODGRUPOPROD>='01040000' AND CODGRUPOPROD<='01049999'))
GROUP BY ITE.CODVEND
        ,VEN.APELIDO
        ,VEN.CODEMP) AS ELETROS
INNER JOIN (
SELECT 'MOVEIS' [GRUPO]
      ,(
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1110,1101,1112) THEN ITE.VLRTOT-ITE.VLRDESC END),0) -
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1201) THEN ITE.VLRTOT-ITE.VLRDESC END),0)) [QTDNEG]
      ,ITE.CODVEND
      ,VEN.APELIDO
      ,VEN.CODEMP
FROM TGFCAB CAB
    ,TGFITE ITE
    ,TGFPRO PRO
    ,TGFVEN VEN
WHERE CAB.NUNOTA = ITE.NUNOTA
  AND VEN.TIPVEND='V'
  AND PRO.CODPROD = ITE.CODPROD
  AND ITE.CODVEND = VEN.CODVEND
  AND YEAR(CAB.DTNEG) = @YEAR
  AND MONTH(CAB.DTNEG) = @MONTH
  AND VEN.CODEMP=@EMP
  AND CAB.CODTIPOPER IN (1110,1101,1112,1201)
  AND ITE.CODVEND NOT IN (0,22,202)
  AND ((CODGRUPOPROD>='01030000' AND CODGRUPOPROD<='01039999') OR
       (CODGRUPOPROD>='01050000' AND CODGRUPOPROD<='01999999'))
GROUP BY ITE.CODVEND
        ,VEN.APELIDO
        ,VEN.CODEMP) AS MOVEIS
ON ELETROS.CODVEND = MOVEIS.CODVEND
-------------------------------
) UNION ALL (
-------------------------------
SELECT 
NULL AS [CODEMP]
,NULL AS [CODVEND]
,NULL AS [APELIDO]
,NULL AS [TOTAL]
     ,((100*ELETROS.QTDNEG)/ (ELETROS.QTDNEG+MOVEIS.QTDNEG)) [ELETROS]
      ,((100*MOVEIS.QTDNEG)/  (ELETROS.QTDNEG+MOVEIS.QTDNEG))[MOVEIS]

FROM (SELECT 'ELETROS' [GRUPO]
     ,(
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1110,1101,1112) THEN ITE.VLRTOT-ITE.VLRDESC END),0) -
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1201) THEN ITE.VLRTOT-ITE.VLRDESC END),0)) [QTDNEG]
,CAB.CODEMP
FROM TGFCAB CAB
    ,TGFITE ITE
    ,TGFPRO PRO
WHERE CAB.NUNOTA = ITE.NUNOTA
  AND PRO.CODPROD = ITE.CODPROD
  AND YEAR(CAB.DTNEG) = @YEAR
  AND MONTH(CAB.DTNEG) = @MONTH
  AND CAB.CODTIPOPER IN (1110,1101,1112,1201)
  AND ((CODGRUPOPROD>='01010000' AND CODGRUPOPROD<='01029999') OR 
       (CODGRUPOPROD>='01040000' AND CODGRUPOPROD<='01049999'))
  AND CAB.CODEMP=@EMP
GROUP BY CAB.CODEMP) AS ELETROS
INNER JOIN
 (
SELECT 'MOVEIS' [GRUPO]
      ,(
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1110,1101,1112) THEN ITE.VLRTOT-ITE.VLRDESC END),0) -
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1201) THEN ITE.VLRTOT-ITE.VLRDESC END),0)) [QTDNEG]
,CAB.CODEMP
FROM TGFCAB CAB
    ,TGFITE ITE
    ,TGFPRO PRO
WHERE CAB.NUNOTA = ITE.NUNOTA
  AND PRO.CODPROD = ITE.CODPROD
  AND YEAR(CAB.DTNEG) = @YEAR
  AND MONTH(CAB.DTNEG) = @MONTH
  AND CAB.CODTIPOPER IN (1110,1101,1112,1201)
  AND ((CODGRUPOPROD>='01030000' AND CODGRUPOPROD<='01039999') OR
       (CODGRUPOPROD>='01050000' AND CODGRUPOPROD<='01999999'))
  AND CAB.CODEMP=@EMP
GROUP BY CAB.CODEMP
) AS MOVEIS
ON ELETROS.CODEMP = MOVEIS.CODEMP
-------------------------------------
)) AS RESULT_SET
