DECLARE @YEAR int
SET @YEAR=2018
DECLARE @MONTH int
SET @MONTH=06
DECLARE @VEND int
SET @VEND=17

SELECT ELETROS.CODVEND
      ,ELETROS.QTDNEG [ELETROS]
      ,MOVEIS.QTDNEG [MOVEIS]
FROM (
SELECT 'ELETROS' [GRUPO]
      ,(
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1110,1101,1112) THEN ITE.VLRTOT-ITE.VLRDESC END),0) -
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1201) THEN ITE.VLRTOT-ITE.VLRDESC END),0)) [QTDNEG]
      ,ITE.CODVEND
FROM TGFCAB CAB
    ,TGFITE ITE
    ,TGFPRO PRO
    ,TGFVEN VEN
WHERE CAB.NUNOTA = ITE.NUNOTA
  AND PRO.CODPROD = ITE.CODPROD
  AND ITE.CODVEND = VEN.CODVEND
  AND YEAR(CAB.DTNEG) = @YEAR
  AND MONTH(CAB.DTNEG) = @MONTH
  AND CAB.CODTIPOPER IN (1110,1101,1112,1201)
  AND ITE.CODVEND NOT IN (0,22,202)
  AND ((CODGRUPOPROD>='01010000' AND CODGRUPOPROD<='01029999') OR 
       (CODGRUPOPROD>='01040000' AND CODGRUPOPROD<='01049999'))
GROUP BY ITE.CODVEND) AS ELETROS
INNER JOIN (
SELECT 'MOVEIS' [GRUPO]
      ,(
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1110,1101,1112) THEN ITE.VLRTOT-ITE.VLRDESC END),0) -
       ISNULL(SUM(CASE WHEN CAB.CODTIPOPER IN (1201) THEN ITE.VLRTOT-ITE.VLRDESC END),0)) [QTDNEG]
      ,ITE.CODVEND
FROM TGFCAB CAB
    ,TGFITE ITE
    ,TGFPRO PRO
    ,TGFVEN VEN
WHERE CAB.NUNOTA = ITE.NUNOTA
  AND PRO.CODPROD = ITE.CODPROD
  AND ITE.CODVEND = VEN.CODVEND
  AND YEAR(CAB.DTNEG) = @YEAR
  AND MONTH(CAB.DTNEG) = @MONTH
  AND CAB.CODTIPOPER IN (1110,1101,1112,1201)
  AND ITE.CODVEND NOT IN (0,22,202)
  AND ((CODGRUPOPROD>='01030000' AND CODGRUPOPROD<='01039999') OR
       (CODGRUPOPROD>='01050000' AND CODGRUPOPROD<='01999999'))
GROUP BY ITE.CODVEND) AS MOVEIS
ON ELETROS.CODVEND = MOVEIS.CODVEND
