SELECT TOP 10
  GRU.DESCRGRUPOPROD
  ,[JAN] = SUM(CASE WHEN MONTH(CAB.DTNEG)=1 THEN ITE.VLRTOT END)
  ,[FEV] = SUM(CASE WHEN MONTH(CAB.DTNEG)=2 THEN ITE.VLRTOT END)
  ,[MAR] = SUM(CASE WHEN MONTH(CAB.DTNEG)=3 THEN ITE.VLRTOT END)
  ,[ABR] = SUM(CASE WHEN MONTH(CAB.DTNEG)=4 THEN ITE.VLRTOT END)
  ,[MAI] = SUM(CASE WHEN MONTH(CAB.DTNEG)=5 THEN ITE.VLRTOT END)
  ,[JUN] = SUM(CASE WHEN MONTH(CAB.DTNEG)=6 THEN ITE.VLRTOT END)
  ,[JUL] = SUM(CASE WHEN MONTH(CAB.DTNEG)=7 THEN ITE.VLRTOT END)
  ,[AGO] = SUM(CASE WHEN MONTH(CAB.DTNEG)=8 THEN ITE.VLRTOT END)
  ,[SET] = SUM(CASE WHEN MONTH(CAB.DTNEG)=9 THEN ITE.VLRTOT END)
  ,[OUT] = SUM(CASE WHEN MONTH(CAB.DTNEG)=10 THEN ITE.VLRTOT END)
  ,[NOV] = SUM(CASE WHEN MONTH(CAB.DTNEG)=11 THEN ITE.VLRTOT END)
  ,[DEZ] = SUM(CASE WHEN MONTH(CAB.DTNEG)=12 THEN ITE.VLRTOT END)
  ,SUM(ITE.VLRTOT) [TOTAL]
FROM
  TGFCAB CAB
  ,TGFITE ITE
  ,TGFPRO PRO
  ,TGFGRU GRU

WHERE
  CAB.NUNOTA = ITE.NUNOTA
  AND PRO.CODPROD = ITE.CODPROD
  AND PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
  AND CAB.CODTIPOPER IN (1112, 1110, 1101)
  AND YEAR(CAB.DTNEG)=2016

GROUP BY
  GRU.DESCRGRUPOPROD

ORDER BY
  SUM(ITE.VLRTOT) DESC
