SELECT TOP 10
  GRU.DESCRGRUPOPROD
  ,[2014] = SUM(CASE WHEN YEAR(CAB.DTNEG)=2014 THEN ITE.VLRTOT END)
  ,[2015] = SUM(CASE WHEN YEAR(CAB.DTNEG)=2015 THEN ITE.VLRTOT END)
  ,[2016] = SUM(CASE WHEN YEAR(CAB.DTNEG)=2016 THEN ITE.VLRTOT END)
  ,[2017] = SUM(CASE WHEN YEAR(CAB.DTNEG)=2017 THEN ITE.VLRTOT END)
  ,SUM(ITE.VLRTOT) [TOTAL]
FROM
  TGFCAB CAB
  ,TGFITE ITE
  ,TGFPRO PRO
  ,TGFGRU GRU

WHERE
  CAB.NUNOTA = ITE.NUNOTA
  AND PRO.CODPROD = ITE.CODPROD
  AND PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
  AND CAB.CODTIPOPER IN (1112, 1110, 1101)

GROUP BY
  GRU.DESCRGRUPOPROD

ORDER BY
  SUM(ITE.VLRTOT) DESC
